// SPDX-License-Identifier: MIT
/**
 * The methodology section. Not a footnote — a real section, linked from the
 * rail. Stating the limits plainly is what makes this read as research rather
 * than advocacy, so nothing here is softened.
 *
 * Every number is pulled from headline.json and every source row from
 * sources.json, both generated by the pipeline. The section follows the same
 * order as the README — allocation finding, demonstration, aggregate, negative
 * space — because a site and a repository that tell different stories about the
 * same data are worse than either alone.
 */

import type { Dataset } from "../lib/data";
import { rampStops } from "../lib/ramp";
import * as fmt from "../lib/format";

export function mountMethodology(root: HTMLElement, data: Dataset): void {
  const meta = data.languages.meta;
  const figures = data.headline.figures;
  const stops = rampStops();

  /** A figure rendered with its referent attached, so it can be checked. */
  const fig = (key: string): string => {
    const f = figures[key];
    if (!f) return `<span class="fig fig-missing">[missing figure: ${key}]</span>`;
    const ref = Object.entries(f.referent)
      .filter(([k]) => k !== "examples")
      .map(([k, v]) => `${k}: ${Array.isArray(v) ? v.join(", ") : v}`)
      .join(" · ");
    return (
      `<span class="fig tabular" tabindex="0" title="${f.statistic} — ${ref}">` +
      `${f.text}</span>`
    );
  };

  const substituted = data.sources.sources.filter((s) => s.substituted);
  const canonical = data.sources.sources.filter(
    (s) => !s.substituted && s.kind !== "font"
  );

  // Degrade visibly rather than silently: a reader must not mistake a stale
  // deploy for a study that never recorded its provenance.
  const degraded =
    Object.keys(figures).length === 0 || data.sources.sources.length === 0;
  const degradedNotice = degraded
    ? `<p class="panel degraded" role="status">
         This page could not load its generated figures or provenance record, so
         some numbers and the source table are missing below. That is a stale
         deployment, not a study without provenance — the full record is in
         <a href="https://github.com/lwdata75/unallocated/blob/main/METHODOLOGY.md">METHODOLOGY.md</a>
         and <code>pipeline/sources.toml</code>.
       </p>`
    : "";

  root.innerHTML = `
    <div class="editorial">
      <div class="section-head">
        <h2>Methodology and limits</h2>
        <p class="caption">
          Every number on this page is generated from the pipeline's exported
          data. Hover any figure to see the statistic and sample it refers to.
        </p>
      </div>

      ${degradedNotice}

      <h3>The claim, in order</h3>
      <p>
        <strong>Vocabulary allocation is a scoped choice, not a general virtue.</strong>
        BLOOM was built multilingual-first with a 250k vocabulary. Its median
        fertility across all ${meta.n_sentences.flores ? "204" : ""} languages is
        ${fig("median_fertility_bloom_vs_o200k")} for OpenAI's o200k — slightly
        worse overall. On Bengali it costs ${fig("bengali_bloom_vs_o200k")}. It
        wins on ${fig("bloom_beats_o200k_count")} languages and loses on the rest.
        ROOTS, BLOOM's training corpus, covered roughly 46 languages, and the
        boundary of that list is visible in the measurements. Nobody bought
        "multilingual"; they bought a specific list.
      </p>
      <p>
        <strong>The demonstration.</strong> Telugu's median FLORES-200 sentence
        costs ${fig("telugu_median_tokens")} tokens, against
        ${fig("english_median_tokens")} for the same sentences in English.
        Decomposed: ${fig("telugu_floor_and_neglect")}. On GPT-2,
        ${fig("telugu_glyphless_share")} of Telugu tokens contain no character at
        all — they are byte fragments of characters the vocabulary cannot
        represent whole. This is the clearest single case, but it is evidence for
        the claim above, not the claim itself.
      </p>
      <p>
        <strong>The aggregate.</strong> On GPT-2,
        ${fig("gpt2_over_thresholds")}. On o200k, ${fig("o200k_over_thresholds")}.
      </p>
      <p>
        <strong>The negative space.</strong> Llama-3 extends cl100k_base by
        roughly 28,000 tokens. For ${fig("llama3_identical_to_cl100k")} languages
        it reports fertility identical to cl100k to the last decimal — Telugu
        sits at ${fig("telugu_llama3_and_cl100k")} — because none of those
        additions went to them. That is falsifiable: add coverage for any of
        those languages and the count drops.
      </p>

      <h3>What this does not claim</h3>
      <ul>
        <li><strong>Nothing about model quality.</strong> Fertility is a property
          of a tokenizer, not of a model. A model with a bad tokenizer may still
          be the best available.</li>
        <li><strong>No ranking of model versions.</strong> Comparisons are between
          tokenizer <em>families</em>, one representative each, and every axis
          label says so. Not a leaderboard.</li>
        <li><strong>No currency figure that is anything but illustrative.</strong>
          Per-token pricing varies by provider, by model and between input and
          output, and changes often. A multiplier is a measurement; a price is a
          worked example.</li>
        <li><strong>No causal claim about downstream behaviour.</strong> High
          fertility plausibly degrades quality and effective context, arguably the
          more serious harm — but this measures token counts, not capability.</li>
        <li><strong>No claim that the floor is the true floor.</strong> It is the
          best of the eight tokenizers here, so it is an upper bound. A better
          tokenizer would lower it and make every neglect figure larger.</li>
      </ul>

      <h3>What is being measured</h3>
      <p>
        For each language and tokenizer, fertility is the median ratio of token
        counts against English, computed <em>per aligned sentence pair</em> and
        then medianed. FLORES-200 and MASSIVE are both sentence-aligned, so
        sentence <em>n</em> in Telugu carries the same meaning as sentence
        <em>n</em> in English and the ratio measures cost per unit of meaning
        rather than cost per unit of text. Dividing one median by the other would
        look similar and would quietly throw the pairing away.
      </p>
      <p>
        The floor is the lowest median token count any tokenizer here achieves
        for a language — a stand-in for the cost inherent to its writing system.
        Neglect is everything above that floor.
      </p>

      <h3>Provenance</h3>
      <p>
        Every input is recorded with its source, revision, hash and licence.
        ${canonical.length} of ${canonical.length + substituted.length} corpora and
        tokenizers come from their canonical first-party source.
        ${substituted.length} are substituted, both because the canonical
        repository is access-gated rather than unavailable:
      </p>
      <ul class="sources">
        ${substituted
          .map(
            (s) => `
          <li>
            <code>${s.key}</code> — canonical <code>${s.canonical}</code> is gated;
            using <code>${s.resolved}</code>.
            <span class="source-evidence">${s.verified_against}</span>
          </li>`
          )
          .join("")}
      </ul>
      <p>
        Equivalence is asserted on behaviour, not on the hash of the tokenizer
        file: legitimate mirrors differ in chat templates and metadata while
        tokenizing identically. Two sources count as equivalent when they agree
        on vocabulary size and on the token ids for a fixed 32-string probe set
        spanning Latin, CJK, Indic, Arabic, Hebrew, Thai, Myanmar, Ethiopic,
        Georgian, Greek, Cyrillic, emoji, ZWJ sequences, combining marks and
        whitespace edge cases.
      </p>
      <p>
        The corpora are <em>not</em> substituted, which is easy to get backwards.
        FLORES-200 comes from Meta's own distribution and MASSIVE from Amazon's;
        the HuggingFace paths are the mirrors. FLORES-200 is also not FLORES+ —
        different releases with different language inventories, and a gate
        asserts which one was loaded.
      </p>

      <h3>Sources</h3>
      <ul>
        <li><strong>FLORES-200</strong>, ${fmt.tokens(meta.n_sentences.flores)}
          sentences of Wikipedia-register prose in 204 language-script pairs,
          professionally translated. CC-BY-SA-4.0.</li>
        <li><strong>MASSIVE 1.1</strong>, a seeded
          ${fmt.tokens(meta.n_sentences.massive)}-utterance sample across 52
          locales, used to check the finding survives a change of register.
          CC-BY-4.0.</li>
        <li>Language family and macro-region from <strong>Glottolog</strong>
          (CC-BY-4.0); speaker counts from <strong>Wikidata</strong> P1098 (CC0).
          Ethnologue's figures are more complete but licence-restricted, so they
          are not used.</li>
      </ul>

      <h3>Caveats that matter</h3>
      <ul>
        <li><strong>FLORES is translationese.</strong> Every non-English sentence
          is a translation of an English source. That is what makes it aligned and
          usable, but translated prose tracks English structure more closely than
          native writing. If anything this understates the surcharge. MASSIVE is a
          partial control and agrees closely: Spearman ρ between the two corpora
          is ${fig("cross_corpus_rank_correlation")} across the eight tokenizers.</li>
        <li><strong>Speaker counts are contested.</strong> They depend on whether
          second-language speakers are counted, on how a macrolanguage is
          subdivided, and on census politics. Used for dot size and ordering, not
          for any quantitative claim.</li>
        <li><strong>Median, not mean.</strong> A handful of pathological sentences
          cannot drive the result. The p90 is reported alongside because tail cost
          determines whether a document fits in a context window.</li>
      </ul>

      <h3>Reading the colour</h3>
      <p>
        The ramp is diverging and anchored at parity, so a language that costs the
        same as English reads as neutral rather than as the good end of a scale.
      </p>
      <ul class="ramp-legend">
        ${stops
          .map(
            (s) =>
              `<li><span class="swatch" style="background:${s.colour}"></span><span class="tabular">${fmt.multiplier(s.value)}</span></li>`
          )
          .join("")}
      </ul>

      <h3>Validation</h3>
      <p>
        The pipeline fails rather than exports. Gates run as tests before any
        JSON is written: English fertility exactly 1.0 for every tokenizer; full
        coverage across both corpora; a decode round-trip per tokenizer; no
        language below 0.85× without a written explanation; cross-corpus rank
        correlation above 0.7; every recorded source still matching what was
        loaded; and every figure in the documentation re-rendering identically
        from this data.
      </p>

      <p class="colophon">
        Data generated ${meta.generated}. Full method, provenance table and
        licences in
        <a href="https://github.com/lwdata75/unallocated/blob/main/METHODOLOGY.md">METHODOLOGY.md</a>;
        machine-readable provenance in
        <a href="data/sources.json">sources.json</a> and every quoted figure in
        <a href="data/headline.json">headline.json</a>;
        pipeline and site in
        <a href="https://github.com/lwdata75/unallocated">the repository</a>.
      </p>
    </div>
  `;
}
