// SPDX-License-Identifier: MIT
/**
 * The methodology section. Not a footnote — a real section, linked from the
 * rail. Stating the limits plainly is what makes this read as research rather
 * than advocacy, so nothing here is softened.
 *
 * The study's argument used to live at the top of this section, which buried it:
 * "Methodology and limits" is the one heading that tells a reader they may skip
 * what follows. It now has its own section — see views/claim.ts — and what is
 * left here is what a methodology section is actually for: what was measured,
 * where it came from, what it does not claim, and how it is checked.
 *
 * Every number is pulled from headline.json and every source row from
 * sources.json, both generated by the pipeline.
 */

import type { Dataset } from "../lib/data";
import { rampStops } from "../lib/ramp";
import { figureSpan } from "../lib/figures";
import * as fmt from "../lib/format";

export function mountMethodology(root: HTMLElement, data: Dataset): void {
  const meta = data.languages.meta;
  const figures = data.headline.figures;
  const stops = rampStops();

  /** A figure rendered with its referent attached, so it can be checked. */
  const fig = (key: string): string => figureSpan(figures, key);

  const substituted = data.sources.sources.filter((s) => s.substituted);
  const canonical = data.sources.sources.filter(
    (s) => !s.substituted && s.kind !== "font"
  );

  // Degrade visibly rather than silently: a reader must not mistake a stale
  // deploy for a study that never recorded its provenance.
  const degraded =
    Object.keys(figures).length === 0 || data.sources.sources.length === 0;
  const degradedNotice = degraded
    ? `<p class="panel degraded" role="status">
         This page could not load its generated figures or provenance record, so
         some numbers and the source table are missing below. That is a stale
         deployment, not a study without provenance — the full record is in
         <a href="https://github.com/lwdata75/unallocated/blob/main/METHODOLOGY.md">METHODOLOGY.md</a>
         and <code>pipeline/sources.toml</code>.
       </p>`
    : "";

  root.innerHTML = `
    <div class="editorial">
      <div class="section-head">
        <p class="step-mark">Eight</p>
        <h2>Method and provenance</h2>
        <p class="caption">
          Every number on this site is generated from the pipeline's exported
          data. Hover any figure to see the statistic and the sample it refers
          to. What the study refuses to claim is the section above this one.
        </p>
      </div>

      ${degradedNotice}

      <h3>What is being measured</h3>
      <p>
        For each language and tokenizer, fertility is the median ratio of token
        counts against English, computed <em>per aligned sentence pair</em> and
        then medianed. FLORES-200 and MASSIVE are both sentence-aligned, so
        sentence <em>n</em> in Telugu carries the same meaning as sentence
        <em>n</em> in English and the ratio measures cost per unit of meaning
        rather than cost per unit of text. Dividing one median by the other would
        look similar and would quietly throw the pairing away.
      </p>
      <p>
        The floor is the lowest median token count any tokenizer here achieves
        for a language — a stand-in for the cost inherent to its writing system.
        Neglect is everything above that floor.
      </p>

      <h3>How the numbers are produced</h3>
      <p>
        Nothing on this site is computed in your browser except the free-text
        box. Every figure is the output of a pipeline that runs end to end, fails
        rather than exports when a check does not hold, and writes four JSON files
        the page then only has to draw. The stages, in order:
      </p>
      <ol class="process">
        <li>
          <strong>Acquire.</strong> FLORES-200 is downloaded from Meta's own
          distribution and MASSIVE from Amazon's, as archives, and both are
          checksummed against pinned hashes before anything is read out of them.
          Tokenizer files are fetched per family and recorded with the revision
          they came from. Re-runs work from a local cache, so the pipeline is
          reproducible offline once primed.
        </li>
        <li>
          <strong>Align.</strong> The corpora are joined on sentence identity, not
          on row order. MASSIVE is joined on its utterance ids across all 52
          locales and reduced to the ids present in <em>every</em> locale, then
          subsampled to ${fmt.tokens(meta.n_sentences.massive)} with a fixed seed
          so the sample is the same on every run. An assertion then demands equal
          row counts and identical id sequences across every language, and raises
          rather than warns: a silent misalignment would compare unrelated
          sentences and produce numbers that look entirely plausible.
        </li>
        <li>
          <strong>Tokenize.</strong> Each corpus is encoded once per tokenizer,
          without special tokens — a chat template would add a constant to every
          count and inflate the languages with the shortest sentences most. Token
          counts are cached as integer arrays per corpus and tokenizer, which is
          what makes re-running cheap. Vocabulary size is read off the loaded
          tokenizer rather than its config file, because the config figure is
          often padded and would misstate what was actually available.
        </li>
        <li>
          <strong>Aggregate.</strong> Per language and tokenizer: median tokens
          per sentence, fertility as the median <em>per-pair</em> ratio against
          English, the 90th percentile of that same ratio, and characters per
          token. Then per language: the floor across tokenizers, and neglect as
          the excess above it. Medians throughout, so a handful of pathological
          sentences cannot drive a result; the p90 is carried alongside because
          tail cost is what decides whether a document fits a context window.
        </li>
        <li>
          <strong>Gate.</strong> The checks below run as tests <em>before</em>
          export. A failure stops the build with no JSON written, which is the
          only arrangement under which a check is worth anything.
        </li>
        <li>
          <strong>Export and re-render.</strong> Four files are written — the
          measurements, the sample sentences with token boundaries, the quoted
          figures with their referents, and the provenance record. Then every
          figure quoted in the documentation is re-rendered from that data and
          compared against what is committed, so a number cannot drift out of
          sync with the pipeline that produced it. That check caught a
          hand-typed multiplier and a mismatched English token count during this
          build.
        </li>
      </ol>

      <h3>Assumptions, stated plainly</h3>
      <p>
        These are choices, not facts. Each one could reasonably have been made
        differently, and each would move the numbers.
      </p>
      <ul>
        <li><strong>English is the pivot.</strong> Every ratio is against English,
          which makes English 1.0 by construction and not by merit. A study
          pivoted on Hindi would produce a different-looking table with the same
          underlying content.</li>
        <li><strong>A sentence is the unit of meaning.</strong> Aligned sentence
          pairs are treated as carrying the same content in both languages. That
          is what FLORES is built for, and it is still an approximation:
          translations add and drop material.</li>
        <li><strong>The floor is the best of eight.</strong> There is no
          independent measure of what a script inherently requires, so the best
          tokenizer here stands in for it. That makes every neglect figure a
          lower bound on the true neglect.</li>
        <li><strong>One tokenizer per family.</strong> Families ship several
          checkpoints; one representative was measured for each, chosen for
          being the family's base vocabulary rather than the newest release.</li>
        <li><strong>Median over mean, throughout.</strong> Robust to outliers,
          but it discards information about the tail — which is why the p90 is
          also exported.</li>
        <li><strong>Speaker counts come from Wikidata.</strong> They are used for
          dot size and ordering only, never for a quantitative claim, because
          they are genuinely contested.</li>
      </ul>

      <h3>Provenance</h3>
      <p>
        Every input is recorded with its source, revision, hash and licence.
        ${canonical.length} of ${canonical.length + substituted.length} corpora and
        tokenizers come from their canonical first-party source.
        ${substituted.length} are substituted, both because the canonical
        repository is access-gated rather than unavailable:
      </p>
      <ul class="sources">
        ${substituted
          .map(
            (s) => `
          <li>
            <code>${s.key}</code> — canonical <code>${s.canonical}</code> is gated;
            using <code>${s.resolved}</code>.
            <span class="source-evidence">${s.verified_against}</span>
          </li>`
          )
          .join("")}
      </ul>
      <p>
        Equivalence is asserted on behaviour, not on the hash of the tokenizer
        file: legitimate mirrors differ in chat templates and metadata while
        tokenizing identically. Two sources count as equivalent when they agree
        on vocabulary size and on the token ids for a fixed 32-string probe set
        spanning Latin, CJK, Indic, Arabic, Hebrew, Thai, Myanmar, Ethiopic,
        Georgian, Greek, Cyrillic, emoji, ZWJ sequences, combining marks and
        whitespace edge cases.
      </p>
      <p>
        The corpora are <em>not</em> substituted, which is easy to get backwards.
        FLORES-200 comes from Meta's own distribution and MASSIVE from Amazon's;
        the HuggingFace paths are the mirrors. FLORES-200 is also not FLORES+ —
        different releases with different language inventories, and a gate
        asserts which one was loaded.
      </p>

      <h3>Sources</h3>
      <ul>
        <li><strong>FLORES-200</strong>, ${fmt.tokens(meta.n_sentences.flores)}
          sentences of Wikipedia-register prose in 204 language-script pairs,
          professionally translated. CC-BY-SA-4.0.</li>
        <li><strong>MASSIVE 1.1</strong>, a seeded
          ${fmt.tokens(meta.n_sentences.massive)}-utterance sample across 52
          locales, used to check the finding survives a change of register.
          CC-BY-4.0.</li>
        <li>Language family and macro-region from <strong>Glottolog</strong>
          (CC-BY-4.0); speaker counts from <strong>Wikidata</strong> P1098 (CC0).
          Ethnologue's figures are more complete but licence-restricted, so they
          are not used.</li>
      </ul>

      <h3>Reading the colour</h3>
      <p>
        The ramp is sequential and single-hue: lightness falls monotonically from
        parity to the worst case measured, so a higher cost reads as more ink and
        never as a worse colour. That is deliberate. A red-to-green ramp would
        say that a language whose script needs more tokens is doing something
        wrong, which is the opposite of the finding. It also means the ramp
        carries its whole signal in lightness, so it survives any form of colour
        vision deficiency, and that a language sitting at parity is drawn almost
        blank — which is the correct reading. No surcharge, no ink.
      </p>
      <ul class="ramp-legend">
        ${stops
          .map(
            (s) =>
              `<li><span class="swatch" style="background:${s.colour}"></span><span class="tabular">${fmt.multiplier(s.value)}</span></li>`
          )
          .join("")}
      </ul>

      <h3>The gates, and what each one catches</h3>
      <p>
        Every check below runs as a test before any JSON is written, so a
        failure produces no export at all. They are listed with the specific
        mistake each is there to catch, because a check whose failure mode you
        cannot name is decoration.
      </p>
      <table class="gates">
        <caption>Run on every pipeline execution; the build stops on any failure.</caption>
        <thead>
          <tr><th scope="col">Gate</th><th scope="col">What it catches</th></tr>
        </thead>
        <tbody>
          <tr>
            <th scope="row">English fertility is exactly 1.0</th>
            <td>A broken pivot. If the ratio of English against itself is not 1,
              the pairing has been lost somewhere upstream and every other number
              is meaningless.</td>
          </tr>
          <tr>
            <th scope="row">Full coverage in both corpora</th>
            <td>A language silently dropped by a join, which would quietly remove
              exactly the hardest cases.</td>
          </tr>
          <tr>
            <th scope="row">Decode round-trip per tokenizer</th>
            <td>A tokenizer that is normalising text before encoding it. One does
              — Qwen applies NFC — and it is handled explicitly rather than
              hidden, because unnoticed normalisation would understate cost for
              exactly the scripts that use combining marks.</td>
          </tr>
          <tr>
            <th scope="row">Token offsets tile the sentence</th>
            <td>Gaps or overlaps in the character spans the tiles are drawn from.
              All eight tokenizers produce overlapping raw offsets where a
              multi-byte character splits across tokens, so this is a real
              condition, not a theoretical one.</td>
          </tr>
          <tr>
            <th scope="row">No language below 0.85×</th>
            <td>A suspiciously cheap language, which usually means a mis-mapped
              locale code. Exceptions must be listed with a written reason.</td>
          </tr>
          <tr>
            <th scope="row">Cross-corpus rank correlation above 0.7</th>
            <td>A result that only holds in Wikipedia-register prose. Measured at
              ${fig("cross_corpus_rank_correlation")} against the spoken-register
              corpus, so it survives the change.</td>
          </tr>
          <tr>
            <th scope="row">Recorded sources still match</th>
            <td>A mirror that changed under the study. Equivalence is re-asserted
              on tokenizer behaviour, not on file hashes.</td>
          </tr>
          <tr>
            <th scope="row">Every quoted figure re-renders</th>
            <td>A number typed by hand into prose and then drifting from the data.
              This one caught two during the build.</td>
          </tr>
        </tbody>
      </table>
      <p>
        ${data.languages.languages.length} languages ×
        ${data.languages.tokenizers.length} tokenizers × 2 corpora, from
        ${fmt.tokens(meta.n_sentences.flores)} aligned sentences and
        ${fmt.tokens(meta.n_sentences.massive)} aligned utterances. The full
        pipeline, its tests and its provenance table are in the repository, and
        the four files this page draws from are linked below — you can check any
        figure here against them without running anything.
      </p>

      <p class="colophon">
        Data generated ${meta.generated}. Full method, provenance table and
        licences in
        <a href="https://github.com/lwdata75/unallocated/blob/main/METHODOLOGY.md">METHODOLOGY.md</a>;
        machine-readable provenance in
        <a href="data/sources.json">sources.json</a> and every quoted figure in
        <a href="data/headline.json">headline.json</a>;
        pipeline and site in
        <a href="https://github.com/lwdata75/unallocated">the repository</a>.
      </p>
    </div>
  `;
}
